GET http://localhost:5000/


### Check Server Status


GET http://localhost:5000/api


### Get all Lawyers

GET http://localhost:5000/api/lawyer


### Add Lawyer


POST http://localhost:5000/api/lawyer
Content-Type: application/json

{
    "email": "ejekanshjain@gmail.com",
    "password": "password"
}


### Login


POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "ejekanshjain@gmail.com",
    "password": "password"
}


###


